jobs:
  include:
  - stage: test
    name: back
    language: java
    services:
    - postgresql
    before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
    cache:
      directories:
      - "$HOME/.gradle/caches/"
      - "$HOME/.gradle/wrapper/"
    before_script: cd back
    script:
    - psql -c 'create database '$DATABASE_NAME';' -U postgres
    - "./gradlew testCoverage"
    after_success:
    - bash <(curl -s https://codecov.io/bash)
  - stage: test
    name: front
    language: node_js
    node_js: node
    cache: yarn
    before_install: cd front
    install: yarn
  - stage: deploy-back
    if: branch = master AND (NOT (type = pull_request))
    language: java
    before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
    cache:
      directories:
      - "$HOME/.gradle/caches/"
      - "$HOME/.gradle/wrapper/"
    before_script: cd back
    script: "./gradlew check -x test"
    deploy:
      provider: heroku
      skip_cleanup: true
      api_key:
        secure: v9m66Ou4ObQAv0qk//jfyztg3MOlMcombPdhnHyN7urx5rYT2rPS1ATffMk7pTixFU8ZTsmAmz42BaY33N9XO8bjIyNKcgQo1Od1TFq4kxGy4v6pzMbxuheKqJdF2XHiA0rV+8mRx30K1Jk4lC30al9/rIjrK+zu63YC5u/+ntNMXk9mvq7Nxp3hLuhPhIJLdyC33GTm/aOGIlBly3vn6L0UjIXYiFWofBJgMW/5soCmFRxbYqohqFDT0tSpdhHnQWHbR0UHR/4sxjpavQJW9KVTRZZup/5BCXVSHLrnr9ROqHceFEhWn1SM0XbK2F/X3SImymo+LPTxxcfSwlaxrxQR5rCwG6Sc7XGHqYzRU3GW7g2NwbbXJGUfR92u9ly46O/QZqUrLuGjhpX/xFwCApDxN5ZMKi3AOO45SnrUb2N5ldTGCVzarzwdWKLUIoF/pP7OCJQ8H2BhwRXLP1irPNVoZuZYuZqyGKgT3trQ5U8YYXacHpcPBecnUrhj1FUIRuRiLis0GCc2fYW+fgYUOxtYLgHwB+EIsMxDRRkqUd4seg+6J39KwT0mo0o6jyX9/P71OrPIfBWQgkEkUiuCgANTEhm7DPPXDpqQHIA0xXfDRHy7G87eYW9q+uCZtJpj9I2aWgNcIvoZM+PzvHAZ7XxPYslMwVHPM/fcc9JxF6c=
      app: sosback
      on:
        repo: AugustoConti/smart-open-space
  - stage: deploy-front
    if: branch = master AND (NOT (type = pull_request))
    language: node_js
    node_js: node
    cache: yarn
    before_script: cd front
    script: skip
    deploy:
      provider: heroku
      skip_cleanup: true
      api_key:
        secure: v9m66Ou4ObQAv0qk//jfyztg3MOlMcombPdhnHyN7urx5rYT2rPS1ATffMk7pTixFU8ZTsmAmz42BaY33N9XO8bjIyNKcgQo1Od1TFq4kxGy4v6pzMbxuheKqJdF2XHiA0rV+8mRx30K1Jk4lC30al9/rIjrK+zu63YC5u/+ntNMXk9mvq7Nxp3hLuhPhIJLdyC33GTm/aOGIlBly3vn6L0UjIXYiFWofBJgMW/5soCmFRxbYqohqFDT0tSpdhHnQWHbR0UHR/4sxjpavQJW9KVTRZZup/5BCXVSHLrnr9ROqHceFEhWn1SM0XbK2F/X3SImymo+LPTxxcfSwlaxrxQR5rCwG6Sc7XGHqYzRU3GW7g2NwbbXJGUfR92u9ly46O/QZqUrLuGjhpX/xFwCApDxN5ZMKi3AOO45SnrUb2N5ldTGCVzarzwdWKLUIoF/pP7OCJQ8H2BhwRXLP1irPNVoZuZYuZqyGKgT3trQ5U8YYXacHpcPBecnUrhj1FUIRuRiLis0GCc2fYW+fgYUOxtYLgHwB+EIsMxDRRkqUd4seg+6J39KwT0mo0o6jyX9/P71OrPIfBWQgkEkUiuCgANTEhm7DPPXDpqQHIA0xXfDRHy7G87eYW9q+uCZtJpj9I2aWgNcIvoZM+PzvHAZ7XxPYslMwVHPM/fcc9JxF6c=
      app: smartopenspace
      on:
        repo: AugustoConti/smart-open-space