version: '3.1'
services:
  database:
    image: "postgres:14.2-alpine"
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_DB=sos
      - POSTGRES_USER=openminded
      - POSTGRES_PASSWORD=openheart
    ports:
      - "6543:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
