version: "3.7"

services:
  app-back:
    image: smart-open-space
    restart: always
    environment:
      SPRING_PROFILE: docker
      APP_PORT: 8080
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:15.0-alpine
    restart: always
    environment:
      POSTGRES_DB: sos
      POSTGRES_USER: openminded
      POSTGRES_PASSWORD: openheart
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "6543:5432"

  pgadmin:
    image: dpage/pgadmin4:6.15
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@asd.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8888:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"

volumes:
  db-data:
  pgadmin-data:
