service: smart-open-space-back

image: cassa97/smart-open-space-back

# Timeout to deploy this service
deploy_timeout: 200

#ssh:
#  user: jocas97

# Deploy to these servers.
servers:
  web:
    - 206.189.236.250

proxy:
  ssl: false
  app_port: 8081
  healthcheck:
    path: /ping

registry:
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD


builder:
  arch: amd64

env:
  clear:
    LOG_LEVEL: INFO
    APP_PORT: 8081
  secret:
    - SPRING_PROFILE
    - FRONTEND_URL
    - CORS_ALLOWED_ORIGINS
    - CORS_ALLOWED_SOCKET_ORIGINS
    - MAIL_SENDER
    - JDBC_DATABASE_URL 
    - JDBC_DATABASE_USERNAME
    - JDBC_DATABASE_PASSWORD
    - MAILGUN_SMTP_SERVER
    - MAILGUN_SMTP_PORT
    - MAILGUN_SMTP_LOGIN
    - MAILGUN_SMTP_PASSWORD
    - JWT_SECRET
    - JWT_EXPIRATION_IN_MINUTES
    - PURGE_PASSWORD


# Use accessory services (secrets come from .kamal/secrets).
# accessories:
#     db:
#       service: db
#       image: postgres:15.0-alpine
#       host: 206.189.236.250
#       port: "127.0.0.1:6543:5432"
#       env:
#         clear:
#           PGDATA: "/var/lib/postgresql/data"
#           POSTGRES_DB: sos
#         secret:
#           - POSTGRES_USER
#           - POSTGRES_PASSWORD
#       volumes:
#         - sos-db-data:/var/lib/postgresql/data
