service: smart-open-space-front

image: cassa97/smart-open-space-front

ssh:
  user: jocvm2

# Deploy to these servers.
servers:
  web:
    hosts:
      - 192.168.184.124

proxy:
  ssl: false
  app_port: 1234
  healthcheck:
    path: /up

registry:
  username: cassa97
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  args:
    # This is API URL of backend (VITE_API_URL)
    API_URL: http://192.168.1.74
    SKIP_HTTPS_IPS: 192.168.184.124,192.168.184.123

env:
  clear:
    UI_PORT: 1234


