service: smart-open-space-front

image: cassa97/smart-open-space-front

ssh:
  user: jocas97

# Deploy to these servers.
servers:
  web:
    - 192.168.1.74

proxy:
  ssl: false
  app_port: 1234
  healthcheck:
    path: /

registry:
  username: cassa97
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  clear:
    UI_PORT: 1234

