{
 "title": "Smart Open Space Back",
 "tags": [ "app" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(jvm_info,application)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_info{application=\"$application\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Uptime - Resume", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(server_request_seconds_count{instance=~\"$instance\", status!~\"5..\"}[$__range])) / sum(increase(server_request_seconds_count{instance=~\"$instance\"}[$__range]))) * 100",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Top 25 - Count",
   "type": "table",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(25, sum by(method, uri) (increase(server_request_seconds_count{instance=~\"$instance\", uri!~\"(.*actuator.*|/)\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 25 -Req/s",
   "type": "table",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(25, sum by(method, uri) (rate(server_request_seconds_count{instance=~\"$instance\", uri!~\"(.*actuator.*|/)\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx Reqs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(server_request_seconds_count{instance=~\"$instance\", status=~\"5..\"}[$__range]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "4xx Reqs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(server_request_seconds_count{instance=~\"$instance\", status=~\"4..\"}[$__range]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Total Reqs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(server_request_seconds_count{instance=~\"$instance\", status=~\"(2..|4..|5..)\"}[$__range]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "2xx Reqs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(server_request_seconds_count{instance=~\"$instance\", status=~\"2..\"}[$__range]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Average Request Count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "2xx Response",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(server_request_seconds_count{application=\"$application\",  instance=~\"$instance\", status=~\"2..\", uri!~\"(.*actuator.*|/)\"}[$__rate_interval])",
       "legendFormat": "{{method}}, {{uri}}, {{status}}, req_jwt={{request_with_jwt}}"
      }
     ]
    },
    {
     "title": "4xx Response",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(server_request_seconds_count{application=\"$application\", instance=~\"$instance\", status=~\"4..\"}[$__rate_interval])",
       "legendFormat": "{{method}}, {{uri}}, {{status}}, req_jwt={{request_with_jwt}}, err_code={{error_code}}, err_msg={{error_message}}, fallback_err={{is_fallback_error}}"
      }
     ]
    },
    {
     "title": "5xx Response",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(server_request_seconds_count{application=\"$application\", instance=~\"$instance\", status=~\"5..\"}[$__rate_interval])",
       "legendFormat": "{{method}}, {{uri}}, {{status}}, req_jwt={{request_with_jwt}}, fallback_err={{is_fallback_error}}, err_code={{error_code}}, err_name={{error_name}}, err_msg={{error_message}}, exception={{exception}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "2xx Response",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "irate(server_request_seconds_sum{application=\"$application\", instance=~\"$instance\", uri!~\"(/|.*(actuator).*)\", method!~\"OPTIONS\", status=~\"2..\"}[$__rate_interval]) / irate(server_request_seconds_count{application=\"$application\", instance=~\"$instance\",method!~\"OPTIONS\", uri!~\"(/|.*(actuator).*)\", status=~\"2..\"}[$__rate_interval])",
       "legendFormat": "{{method}}, {{uri}}, {{status}}, req_jwt={{request_with_jwt}}"
      }
     ]
    },
    {
     "title": "4xx Response",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "irate(server_request_seconds_sum{application=\"$application\", instance=~\"$instance\", status=~\"4..\"}[$__rate_interval]) / irate(server_request_seconds_count{application=\"$application\",  instance=~\"$instance\", status=~\"4..\"}[$__rate_interval])",
       "legendFormat": "{{method}}, {{uri}}, {{status}}, req_jwt={{request_with_jwt}}, err_code={{error_code}}, err_msg={{error_message}}, fallback_err={{is_fallback_error}}"
      }
     ]
    },
    {
     "title": "5xx Response",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "irate(server_request_seconds_sum{application=\"$application\", instance=~\"$instance\", status=~\"5..\"}[$__rate_interval]) / irate(server_request_seconds_count{application=\"$application\", instance=~\"$instance\", status=~\"5..\"}[$__rate_interval])",
       "legendFormat": "{{method}}, {{uri}}, {{status}}, req_jwt={{request_with_jwt}}, fallback_err={{is_fallback_error}}, err_code={{error_code}}, err_name={{error_name}}, err_msg={{error_message}}, exception={{exception}} "
      }
     ]
    }
   ]
  },
  { "title": "Business - User register", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Total Register",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(sos_business_user_register_seconds_count{instance=\"sos-back:8081\"}[$__range]))",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(sos_business_user_register_seconds_count{instance=\"sos-back:8081\", error!~\"none\"}[$__range]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Top - Register errors ",
   "type": "table",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(25, sum by(error, error_code, error_message) (increase(sos_business_user_register_seconds_count{instance=\"sos-back:8081\", error!~\"none\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Register",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(sos_business_user_register_seconds_count{instance=\"sos-back:8081\", error=\"none\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}