DO $$
DECLARE
    seq_start bigint;
BEGIN
    -- Retrieve the next sequence value from hibernate_sequence
    SELECT last_value + 1 INTO seq_start FROM hibernate_sequence;

    -- Restart the sequences generated by hibernate with hibernate_sequence last value
    EXECUTE format('ALTER SEQUENCE IF EXISTS assigned_slot_id_seq RESTART WITH %s', seq_start);
    EXECUTE format('ALTER SEQUENCE IF EXISTS document_id_seq RESTART WITH %s', seq_start);
    EXECUTE format('ALTER SEQUENCE IF EXISTS open_space_id_seq RESTART WITH %s', seq_start);
    EXECUTE format('ALTER SEQUENCE IF EXISTS review_id_seq RESTART WITH %s', seq_start);
    EXECUTE format('ALTER SEQUENCE IF EXISTS room_id_seq RESTART WITH %s', seq_start);
    EXECUTE format('ALTER SEQUENCE IF EXISTS slot_id_seq RESTART WITH %s', seq_start);
    EXECUTE format('ALTER SEQUENCE IF EXISTS talk_id_seq RESTART WITH %s', seq_start);
    EXECUTE format('ALTER SEQUENCE IF EXISTS track_id_seq RESTART WITH %s', seq_start);
    EXECUTE format('ALTER SEQUENCE IF EXISTS users_id_seq RESTART WITH %s', seq_start);
END $$;