config:
  target: "https://smartopenspace.10pines.com"
  phases:
    - duration: 90  # sec
      arrivalRate: 1  # clients per sec
      rampTo: 5  # Increase clients per seconds
      name: Low load test
  defaults:
    headers:
      Content-Type: "application/json"
  processor: "./util.js"
  plugins:
    ensure:
      conditions:
        - expression: "http.response_time.p95 < 1000"

scenarios:
  - flow:
    - function: "getRandomId"
    - get:
        url: "/openSpace/{{ id }}"
        expect:
          - statusCode: 200
          - statusCode: 404
