name: "CD App"

permissions:
  contents: read
  pull-requests: write

# INFO: In case of errors, check actual repository kamal documentations.

on:
  push:
    branches:
      - main

jobs:
  deploy_back:
    if: ${{ vars.IS_ENABLE_KAMAL_CD_BACK == 'true' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    defaults:
      run:
        working-directory: back    
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      KAMAL_REGISTRY_USERNAME: ${{ secrets.KAMAL_REGISTRY_USERNAME }}
      KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
      SPRING_PROFILE: ${{ vars.SPRING_PROFILE }}
      FRONTEND_URL: ${{ vars.FRONTEND_URL }}
      CORS_ALLOWED_ORIGINS: ${{ vars.CORS_ALLOWED_ORIGINS }}
      CORS_ALLOWED_SOCKET_ORIGINS: ${{ vars.CORS_ALLOWED_SOCKET_ORIGINS }}
      MAIL_SENDER: ${{ secrets.MAIL_SENDER }}
      MAILGUN_SMTP_SERVER: ${{ secrets.MAILGUN_SMTP_SERVER }}
      MAILGUN_SMTP_PORT: ${{ secrets.MAILGUN_SMTP_PORT }}
      MAILGUN_SMTP_LOGIN: ${{ secrets.MAILGUN_SMTP_LOGIN }}
      MAILGUN_SMTP_PASSWORD: ${{ secrets.MAILGUN_SMTP_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRATION_IN_MINUTES: ${{ secrets.JWT_EXPIRATION_IN_MINUTES }}
      PURGE_PASSWORD: ${{ secrets.PURGE_PASSWORD }}
      JDBC_DATABASE_URL: ${{ secrets.JDBC_DATABASE_URL }}
      SOS_DB_USER: ${{ secrets.SOS_DB_USER }}
      SOS_DB_PASSWORD: ${{ secrets.SOS_DB_PASSWORD }}
      NEW_RELIC_APP_NAME: ${{ secrets.NEW_RELIC_APP_NAME }}
      NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true

      - name: Install dependencies
        run: gem install kamal

      - uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_BACK_PRIVATE_KEY }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Run kamal deploy command
        run: kamal deploy

  deploy_front:
    if: ${{ vars.IS_ENABLE_KAMAL_CD_FRONT == 'true'  && github.event_name == 'push' && github.ref == 'refs/heads/main'}}
    needs: [deploy_back]
    defaults:
      run:
        working-directory: front    
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      KAMAL_REGISTRY_USERNAME: ${{ secrets.KAMAL_REGISTRY_USERNAME }}
      KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true

      - name: Install dependencies
        run: gem install kamal

      - uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_FRONT_PRIVATE_KEY }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Run kamal deploy command
        run: kamal deploy