name: Front Kamal Command

on:
  push:
    branches:
      - enhancement/kamal-integration # For test (should be removed before merge)
  workflow_dispatch:
    inputs:
      command:
        description: "KAMAL front command to run"
        default: "kamal app details"

jobs:
  command:
    defaults:
      run:
        working-directory: front
    runs-on: ubuntu-latest

    env:
      KAMAL_REGISTRY_USERNAME: ${{ secrets.KAMAL_REGISTRY_USERNAME }}
      KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_FRONT_PRIVATE_KEY }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
      
      - name: Install dependencies
        run: gem install kamal

      - name: Run KAMAL command
        run: ${{ github.event.inputs.command }}